Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false